Added support for Debian/Ubuntu and Mac OSX and improved setup steps

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -1,18 +1,32 @@
 ahoyapi: v1
 version: 0.0.0
 commands:
+
   help:
-    usage: Mac setup commands
-    import: .ahoy/arch.ahoy.yml
+    usage: Development environment setup help
+    cmd: |
+      echo 'For a full docker development environment setup use the following command:
+      ahoy setup
+
+      For a step by step setup use the following commands in order:
+      ahoy deps
+      ahoy virtualbox
+      ahoy docker
+      ahoy nfs
+      ahoy machine'
+
   mac:
     usage: Mac setup commands
-    import: .ahoy/arch.ahoy.yml
+    import: .ahoy/mac.ahoy.yml
+
   debian:
     usage: Debian setup commands
-    import: .ahoy/arch.ahoy.yml
+    import: .ahoy/debian.ahoy.yml
+
   arch:
     usage: Arch Linux setup commands
     import: .ahoy/arch.ahoy.yml
+
   os:
     usage: Checks the Operating System
     cmd: |
@@ -27,6 +41,17 @@ commands:
         fi
       fi
       echo $os
+
+  shell:
+    usage: Prints the default shell
+    cmd: |
+      echo "$(echo $SHELL|rev|cut -d/ -f1|rev)"
+
+  rcfile:
+    usage: Prints the rcfile path of the default shell
+    cmd: |
+      echo "$HOME/.$(ahoy shell)rc"
+
   setup:
     usage: Setup the development environment
     cmd: |
@@ -36,33 +61,7 @@ commands:
         echo "[Error] This OS is not supported."
         exit 1
       fi
-  virtualbox:
-    usage: Install Virtualbox
-    cmd: |
-      if [ "$(ahoy os)" != "" ]; then
-        ahoy $(ahoy os) virtualbox {{args}}
-      else
-        echo "[Error] This OS is not supported."
-        exit 1
-      fi
-  docker:
-    usage: Install Docker
-    cmd: |
-      if [ "$(ahoy os)" != "" ]; then
-        ahoy $(ahoy os) docker {{args}}
-      else
-        echo "[Error] This OS is not supported."
-        exit 1
-      fi
-  nfs:
-    usage: Install NFS
-    cmd: |
-      if [ "$(ahoy os)" != "" ]; then
-        ahoy $(ahoy os) nfs {{args}}
-      else
-        echo "[Error] This OS is not supported."
-        exit 1
-      fi
+
   deps:
     usage: Install dependencies
     cmd: |
@@ -72,6 +71,37 @@ commands:
         echo "[Error] This OS is not supported."
         exit 1
       fi
+
+  virtualbox:
+    usage: Install Virtualbox
+    cmd: |
+      if [ "$(ahoy os)" != "" ]; then
+        ahoy $(ahoy os) virtualbox {{args}}
+      else
+        echo "[Error] This OS is not supported."
+        exit 1
+      fi
+
+  docker:
+    usage: Install Docker
+    cmd: |
+      if [ "$(ahoy os)" != "" ]; then
+        ahoy $(ahoy os) docker {{args}}
+      else
+        echo "[Error] This OS is not supported."
+        exit 1
+      fi
+
+  nfs:
+    usage: Install NFS
+    cmd: |
+      if [ "$(ahoy os)" != "" ]; then
+        ahoy $(ahoy os) nfs {{args}}
+      else
+        echo "[Error] This OS is not supported."
+        exit 1
+      fi
+
   machine:
     usage: Create the "default" Docker machine
     cmd: |
